name: jaguar_query_sqflite_example
description: Example for Jaguar Query sqflite adapter
version: 2.2.9
publish_to: none
homepage: https://github.com/Jaguar-dart/jaguar_orm


environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  jaguar_query_sqflite:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
